---
- name: Set UFW default incoming policy
  community.general.ufw:
    direction: incoming
    policy: "{{ ufw_default_incoming_policy }}"

- name: Set UFW default outgoing policy
  community.general.ufw:
    direction: outgoing
    policy: "{{ ufw_default_outgoing_policy }}"

- name: Allow SSH through firewall
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
  when: ssh_hardening_enabled

- name: Enable UFW firewall
  community.general.ufw:
    state: enabled
    logging: low
  when: ufw_enabled
